export type SeatStatus = "Available" | "Reserved" | "OutOfService";
export type Seat = { id: number; row: string; number: number; price: number; status: SeatStatus; variant?: "standard" | "recliner" };
export type AuditoriumStatus = "Open" | "Maintenance" | "Closed";
export type Auditorium = { id: number; name: string; type: "regular" | "vip"; status: AuditoriumStatus; seats: Seat[] };
export type Movie = { id: number; title: string; synopsis?: string; description?: string; durationMinutes: number; posterUrl: string; rating?: string; experience?: string; tags?: string[]; basePrice?: number; status?: string; genre?: string; cast?: string; releaseDate?: string | null; trailerUrl?: string; archivedAt?: string };
export type MovieWithShowtimes = Movie & { showtimes: Showtime[]; avgRating?: number | null; ratingCount?: number };
export type Showtime = { id: number; movieId: number; startTime: string; endTime?: string; auditorium: string; auditoriumId?: number; auditoriumType?: "regular" | "vip"; experience?: string; price?: number; seats: Seat[] };
export type ShowtimeDraft = { key: string; id?: number; auditoriumId?: number; date: string; time: string; price?: string; errors?: Record<string, string> };
export type ShowtimeWithMovie = Showtime & { movie: Movie | null };
export type AddOn = { id: string; name: string; description: string; price: number; icon: string; comboOf?: string[] };
export type AddOnSelection = { id: string; name: string; price: number };
export type Notification = {
  id: string;
  userId: string;
  role: "admin" | "customer";
  kind: "sold-out" | "now-showing" | "watchlist-sold-out";
  title: string;
  message: string;
  refId?: number;
  createdAt: string;
  readAt?: string | null;
};
export type SeatSnapshot = { row: string; number: number; price: number };
export type Booking = {
  id: string;
  showtimeId: number;
  customerId: string | null;
  userEmail: string;
  movieTitle: string;
  auditorium: string;
  seatSnapshot: SeatSnapshot[];
  addOns: AddOnSelection[];
  paymentMethod: string;
  totalAmount: number;
  createdAt: string;
  isConfirmed: boolean;
  showtime?: ShowtimeWithMovie;
};
export type Store = {
  branches: string[];
  auditoriums: Auditorium[];
  movies: Movie[];
  showtimes: Showtime[];
  bookings: Booking[];
  profiles?: Record<string, CustomerProfile>;
  watchlists?: Record<string, number[]>;
  ratings?: Rating[];
  addOns?: AddOn[];
  notifications?: Notification[];
};
export type AuthUser = { id: string; email: string; role: "admin" | "customer"; metadata?: Record<string, unknown> };
export type CustomerProfile = { name?: string; mobile?: string; paymentPrefs?: string[] };
export type Rating = { id: string; bookingId: string; movieId: number; userId: string; stars: number; updatedAt: string };
export type Dashboard = {
  moviesCurrentlyShowing: number;
  upcomingMovies: number;
  archivedMovies: number;
  todaysBookings: number;
  auditoriumsOpen: number;
  auditoriumsTotal: number;
  auditoriums: { id: number; name: string; type: "regular" | "vip"; status: AuditoriumStatus; seatCount: number }[];
  ticketsSoldToday?: number;
  revenueToday?: number;
  avgOccupancyRate?: number;
};
export const peso = (amount: number) => `₱${amount.toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
