import { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { SiteHeader } from "../components/SiteHeader";
import type { Movie } from "../lib/types";
type Dashboard = { moviesCurrentlyShowing: number; upcomingMovies: number; archivedMovies: number; todaysBookings: number };
export default function Admin() {
  const router = useRouter(); const [stats, setStats] = useState<Dashboard>(); const [movies, setMovies] = useState<Movie[]>([]); const [filter, setFilter] = useState("");
  useEffect(() => { Promise.all([fetch("/api/admin/dashboard"), fetch("/api/admin/movies")]).then(async ([dashboard, catalogue]) => { if (!dashboard.ok || !catalogue.ok) return router.replace("/signin?next=/admin"); setStats(await dashboard.json()); setMovies(await catalogue.json()); }); }, [router]);
  const archive = async (id: number) => { if (!confirm("Archive this movie?")) return; const response = await fetch(`/api/admin/movies/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "archived" }) }); if (response.ok) setMovies(items => items.map(item => item.id === id ? { ...item, status: "archived" } : item)); };
  const signOut = async () => { await fetch("/api/auth/signout", { method: "POST" }); router.push("/"); };
  const cards = stats && [["Now showing", stats.moviesCurrentlyShowing], ["Upcoming", stats.upcomingMovies], ["Archived", stats.archivedMovies], ["Today's bookings", stats.todaysBookings]];
  return <><Head><title>Admin dashboard | CinemaBooking</title></Head><SiteHeader admin /><main className="admin-page shell"><div className="d-flex justify-content-between"><div><p className="kicker">ADMIN PORTAL</p><h1>Good evening.</h1></div><button className="button" onClick={signOut}>Sign out</button></div><p className="muted">A quick view of the cinema today.</p><section className="admin-stats">{cards?.map(([label, value]) => <article className="summary-card" key={String(label)}><span className="muted">{label}</span><strong>{value}</strong></article>)}</section><section className="summary-card admin-placeholder"><p className="kicker">MOVIES</p><div className="section-heading"><h2>Movie records</h2><select value={filter} onChange={e => setFilter(e.target.value)}><option value="">All statuses</option><option value="now showing">now showing</option><option value="coming soon">coming soon</option><option value="archived">archived</option></select></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Title</th><th>Status</th><th>Runtime</th><th /></tr></thead><tbody>{movies.filter(item => !filter || item.status === filter).map(item => <tr key={item.id}><td>{item.title}</td><td><span className="vip-badge">{item.status}</span></td><td>{item.durationMinutes} min</td><td>{item.status !== "archived" && <button className="button" onClick={() => archive(item.id)}>Archive</button>}</td></tr>)}</tbody></table></div></section></main></>;
}
