import { FormEvent, useEffect, useMemo, useState } from "react";
import Head from "next/head";
import { SiteHeader } from "../components/SiteHeader";
import { HeroCarousel } from "../components/HeroCarousel";
import { addOns, Movie, MovieWithShowtimes, peso, Showtime } from "../lib/types";

export default function Home() {
  const [movies, setMovies] = useState<MovieWithShowtimes[]>([]); const [showtimes, setShowtimes] = useState<Showtime[]>([]);
  const [movie, setMovie] = useState<Movie>(); const [showtime, setShowtime] = useState<Showtime>();
  const [seats, setSeats] = useState<number[]>([]); const [extras, setExtras] = useState<string[]>([]); const [step, setStep] = useState(1);
  const [email, setEmail] = useState(""); const [payment, setPayment] = useState("GCash"); const [confirmation, setConfirmation] = useState<string>(); const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetch("/api/movies").then(r => r.json()), fetch("/api/showtimes").then(r => r.json())]).then(([m, s]) => { setMovies(m); setShowtimes(s); }).catch(() => setError("We couldn't load films. Please refresh and try again.")); }, []);
  const movieShows = showtimes.filter(s => s.movieId === movie?.id);
  const selectedSeats = showtime?.seats.filter(s => seats.includes(s.id)) ?? [];
  const total = selectedSeats.reduce((sum, s) => sum + s.price, 0) + extras.reduce((sum, id) => sum + (addOns.find(a => a.id === id)?.price ?? 0), 0);
  const chooseMovie = (item: MovieWithShowtimes) => { setMovie(item); setShowtime(undefined); setSeats([]); setStep(2); };
  const next = () => { if (step === 1 && !movie) return setError("Choose a film first."); if (step === 2 && !showtime) return setError("Choose a showtime first."); if (step === 3 && !seats.length) return setError("Choose at least one seat."); setError(""); setStep(Math.min(5, step + 1)); };
  const book = async (event: FormEvent) => { event.preventDefault(); try { const response = await fetch("/api/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ showtimeId: showtime?.id, seatIds: seats, userEmail: email, addOns: extras, paymentMethod: payment }) }); if (!response.ok) throw new Error(await response.text()); const booking = await response.json(); await fetch(`/api/bookings/${booking.id}/confirm`, { method: "POST" }); setConfirmation(booking.id); } catch (err) { setError(err instanceof Error ? err.message : "Could not complete booking."); } };
  const order = <aside className="order-card"><p className="kicker">YOUR ORDER</p><h3>{movie?.title ?? "Select a film"}</h3><p className="muted">{showtime ? new Date(showtime.startTime).toLocaleString() : "Choose a showtime"}</p><div className="order-lines"><span>Seats ({seats.length}) <b>{peso(selectedSeats.reduce((sum, s) => sum + s.price, 0))}</b></span>{extras.map(id => { const a = addOns.find(x => x.id === id)!; return <span key={id}>{a.name}<b>{peso(a.price)}</b></span>; })}</div><div className="order-total"><span>Total</span><strong>{peso(total)}</strong></div></aside>;
  return <><Head><title>CinemaBooking — Your night, your way</title></Head><SiteHeader /><main>
    <section className="hero shell"><div className="hero-copy"><p className="kicker"><span className="live-dot" /> THE CINEMA, REIMAGINED</p><h1>Your night.<br /><em>Your way.</em></h1><p>Premium screens, plush seats, and stories worth staying up for. Make your next movie night memorable.</p><a className="button gold-button" href="#booking">Book your experience →</a></div><HeroCarousel /></section>
    <section className="booking shell" id="booking"><div className="section-heading"><div><p className="kicker">NOW SHOWING</p><h2>What will you watch?</h2><p className="section-intro">One cinema, seven auditoriums, and a seat waiting for you.</p></div></div>
      {error && <p className="error">{error}</p>}
      {!confirmation && <><div className="wizard">{["Select film", "Showtime", "Seats", "Add-ons", "Summary"].map((label, i) => <button className={`wizard-step ${step === i + 1 ? "active" : ""}`} onClick={() => i + 1 <= step && setStep(i + 1)} key={label}><b>0{i + 1}</b><span>{label}</span></button>)}</div>
      {step === 1 && <div className="movie-grid">{movies.filter(item => (item.showtimes?.length ?? 0) > 0).map(item => <article className={`movie-card ${movie?.id === item.id ? "chosen" : ""}`} onClick={() => chooseMovie(item)} key={item.id}><div className="movie-poster" style={{ backgroundImage: `url('${item.posterUrl}')` }}><span className="experience">{item.experience ?? "Standard"}</span></div><div className="movie-info"><div><h3>{item.title}</h3><p>{item.rating ?? "PG-13"} · {Math.floor(item.durationMinutes / 60)}h {item.durationMinutes % 60}m</p></div><span className="movie-price">from {peso(item.basePrice ?? 450)}</span></div><p className="movie-tags">{(item.tags ?? []).map(tag => <span key={tag}>{tag}</span>)}</p></article>)}</div>}
      {step === 2 && <div className="showtime-layout"><div><p className="kicker">AVAILABLE SHOWTIMES</p><div className="showtime-grid">{movieShows.map(item => <button className={`showtime ${showtime?.id === item.id ? "chosen" : ""}`} onClick={() => { setShowtime(item); setSeats([]); setStep(3); }} key={item.id}><b>{new Date(item.startTime).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</b><small>{item.auditoriumType === "vip" && <span className="vip-badge">VIP</span>} {item.experience ?? "Standard"} · {item.auditorium}</small><em>from {peso(item.price ?? item.seats[0]?.price ?? 450)}</em></button>)}</div></div></div>}
      {step === 3 && showtime && <div className="seats-layout"><div className="seat-card"><div className="seat-card-head"><div><p className="kicker">AUDITORIUM {showtime.auditorium}</p><h3>Choose your seats</h3></div><span className="seat-count">{seats.length} selected</span></div><div className="screen">SCREEN</div><div className={`seat-map ${showtime.auditoriumType === "vip" ? "vip" : "regular"}`}>{Array.from(new Set(showtime.seats.map(s => s.row))).map(row => <div className="seat-row" key={row}><span className="row-label">{row}</span>{showtime.seats.filter(s => s.row === row).map(seat => <button disabled={seat.status !== "Available"} className={`seat ${seat.status.toLowerCase()} ${seats.includes(seat.id) ? "selected" : ""}`} onClick={() => setSeats(current => current.includes(seat.id) ? current.filter(id => id !== seat.id) : [...current, seat.id])} key={seat.id}>{seat.number}</button>)}</div>)}</div></div>{order}</div>}
      {step === 4 && <div className="addon-layout"><div><p className="kicker">MAKE IT A NIGHT</p><h3>Something to enjoy?</h3><div className="addon-grid">{addOns.map(item => <label className={`addon ${extras.includes(item.id) ? "chosen" : ""}`} key={item.id}><input type="checkbox" checked={extras.includes(item.id)} onChange={() => setExtras(value => value.includes(item.id) ? value.filter(id => id !== item.id) : [...value, item.id])} /><span className="addon-icon">{item.icon}</span><span><b>{item.name}</b><small>{item.description}</small></span><strong>{peso(item.price)}</strong></label>)}</div></div>{order}</div>}
      {step === 5 && <div className="summary-layout"><div className="summary-card"><p className="kicker">YOUR ITINERARY</p><h3>{movie?.title}</h3><p>{showtime?.auditorium}</p><p>{showtime && new Date(showtime.startTime).toLocaleString()}</p><div className="summary-seats"><span>Seats</span><b>{selectedSeats.map(s => `${s.row}${s.number}`).join(", ")}</b></div><div className="order-total"><span>Total</span><strong>{peso(total)}</strong></div></div><form className="payment-card" onSubmit={book}><p className="kicker">PAYMENT DETAILS</p><h3>How would you like to pay?</h3><div className="payment-methods">{["GCash", "Maya", "Card"].map(method => <label key={method}><input type="radio" checked={payment === method} onChange={() => setPayment(method)} /><span><b>{method}</b><small>Pay with {method}</small></span></label>)}</div><label className="field">Email address<input type="email" value={email} onChange={e => setEmail(e.target.value)} required placeholder="you@example.com" /></label><button className="button gold-button button-full" type="submit">Confirm booking →</button></form></div>}
      <div className="wizard-actions"><button className="button back-button" hidden={step === 1} onClick={() => setStep(step - 1)}>← Back</button><button className="button gold-button" hidden={step >= 5} onClick={next}>Continue →</button></div></>}
      {confirmation && <div className="confirmation"><span className="confirm-icon">✓</span><p className="kicker">YOU'RE ALL SET</p><h2>Enjoy the show.</h2><p>Your booking is confirmed. A receipt is on its way to <strong>{email}</strong>.</p><div><strong>{movie?.title}</strong> · {seats.length} seat{seats.length !== 1 && "s"} · {peso(total)}<br /><small>Confirmation #{confirmation.slice(0, 8).toUpperCase()}</small></div></div>}
    </section><section className="how shell" id="how"><p className="kicker">SIMPLE BY DESIGN</p><h2>Your seat is three steps away.</h2><div className="how-grid">{[["01", "Pick a film", "Browse stories curated for the big screen."], ["02", "Make it yours", "Choose your seats and favorite treats."], ["03", "Walk in ready", "Your booking waits when the lights go down."]].map(([n, h, p]) => <article key={n}><b>{n}</b><h3>{h}</h3><p>{p}</p></article>)}</div></section>
  </main><footer className="footer shell"><strong>CB CinemaBooking</strong><span>Good films. Great company. © 2026</span></footer></>;
}
